name: testing-pipeline
on:
  push:
    branches:
      - develop

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build_test_environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Webtester
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 865522842129.dkr.ecr.us-east-1.amazonaws.com
        export SHA=$(git rev-parse --short "$GITHUB_SHA")
        docker build -f ./tests/Dockerfile -t python-webtester .
        docker tag python-webtester 865522842129.dkr.ecr.us-east-1.amazonaws.com/python-webtester:${SHA}
        docker push 865522842129.dkr.ecr.us-east-1.amazonaws.com/python-webtester:${SHA}

  build_web_application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Website
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 865522842129.dkr.ecr.us-east-1.amazonaws.com
        export SHA=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t website-development .
        docker tag website-development:latest 865522842129.dkr.ecr.us-east-1.amazonaws.com/website-development:${SHA}
        docker push 865522842129.dkr.ecr.us-east-1.amazonaws.com/website-development:${SHA} 
  
  selenium_testing:
    needs: [build_test_environment,build_web_application]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing
        run: |
          export SHA=$(git rev-parse --short "$GITHUB_SHA")
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 865522842129.dkr.ecr.us-east-1.amazonaws.com
          docker pull 865522842129.dkr.ecr.us-east-1.amazonaws.com/website-development:${SHA}
          docker pull 865522842129.dkr.ecr.us-east-1.amazonaws.com/python-webtester:${SHA}
          docker pull selenium/standalone-chrome
          docker network create testing
          docker run --name selenium --network testing -dp 4444:4444 --shm-size="2g" selenium/standalone-chrome
          docker run -dp 80:80 865522842129.dkr.ecr.us-east-1.amazonaws.com/website-development:${SHA}
          sleep 15
          docker run 865522842129.dkr.ecr.us-east-1.amazonaws.com/python-webtester:${SHA}
          
 

          


